//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean entry expected..
        /// </summary>
        internal static string Grammar_BooleanEntryExpected {
            get {
                return ResourceManager.GetString("Grammar_BooleanEntryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte entry expected..
        /// </summary>
        internal static string Grammar_ByteEntryExpected {
            get {
                return ResourceManager.GetString("Grammar_ByteEntryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Entry Expected..
        /// </summary>
        internal static string Grammar_EmptyEntryExpected {
            get {
                return ResourceManager.GetString("Grammar_EmptyEntryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer entry expected..
        /// </summary>
        internal static string Grammar_IntegerEntryExpected {
            get {
                return ResourceManager.GetString("Grammar_IntegerEntryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record header..
        /// </summary>
        internal static string Grammar_InvalidRecordHeader {
            get {
                return ResourceManager.GetString("Grammar_InvalidRecordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record type..
        /// </summary>
        internal static string Grammar_InvalidRecordType {
            get {
                return ResourceManager.GetString("Grammar_InvalidRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry to read..
        /// </summary>
        internal static string Grammar_NoEntry {
            get {
                return ResourceManager.GetString("Grammar_NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String entry expected..
        /// </summary>
        internal static string Grammar_StringEntryExpected {
            get {
                return ResourceManager.GetString("Grammar_StringEntryExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file header..
        /// </summary>
        internal static string Grammar_WrongFileHeader {
            get {
                return ResourceManager.GetString("Grammar_WrongFileHeader", resourceCulture);
            }
        }
    }
}
